Implement Filecoin Flavor
trufflesuite/ganache pull request #2402
Opened 2021-03-08 21:03 UTC by seesemichaelj

Per the request of @tcoulter, this PR targets all of the changes in `ganache` in a single PR. All of the intermediate branches still exist in case someone else wants them

2021-03-08 21:59 UTC, tcoulter requested changes
Nice! Few requests:

2021-03-08 21:59 UTC, tcoulter commented on src/main/index.js
> +if (isDevelopment) {
Can you add a comment above this describing what it's used for?

2021-03-08 21:59 UTC, tcoulter commented on src/main/index.js
> +    if (isDevelopment) {
Same thing here?

2021-03-08 21:59 UTC, tcoulter commented on src/renderer/init/Core.js
>    });
Can you separate these into sections: Common, Ethereum, Filecoin? With very large comment separators. :)

2021-03-08 22:04 UTC, tcoulter approved these changes
Looks good!

2021-03-23 19:39 UTC, davidmurdoch approved these changes

2021-03-23 19:47 UTC, davidmurdoch approved these changes

2021-03-23 19:48 UTC, merged